spring.application.name=Nacho-Ruiz-Velasco-SpringBoot
server.port=3333

spring.datasource.url=jdbc:mysql://localhost:23306/cine_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true